services:
  wallet-backend:
    build: .
    depends_on:
      - postgres
      - redis
      - migrations
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/wallet-backend
    command: air main.go -b 0.0.0.0
  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --save 20 1 --loglevel debug
    volumes:
      - redis:/data
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 1s
      retries: 5
  migrations:
    image: ghcr.io/kukymbr/goose-docker:${GOOSE_DOCKER_TAG}
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
      - GOOSE_MIGRATION_DIR=./migrations
    volumes:
      - ./migrations:/migrations
volumes:
  redis:
    driver: local
  postgres-db: